name: test
on: 
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
     - name: testing
     - run: echo "hello world" 
